### ISSUE TITLE
invalid link

### ISSUE THREAD

**Issue by pchampin** [w3c/sparql-entailment#27]
index.html contains a link to [https://www.w3.org/TR/owl2-mapping-to-rdf/#Satisfaction.2C_Consistency_and_Entailment](view-source:https://www.w3.org/TR/owl2-mapping-to-rdf/#Satisfaction.2C_Consistency_and_Entailment). The URL is correct, but the anchor is not.

I hope this does not block us for FPWD... :-/

**Comment by pfps** [comment]
What tool should be used to find invalid links?

**Comment by gkellogg** [comment]
Use the [W3C Link Checker service](https://validator.w3.org/checklink).

**Comment by pfps** [comment]
Running that on https://pr-preview.s3.amazonaws.com/w3c/sparql-entailment/pull/25.html produces lots of errors.
Running it on https://w3c.github.io/sparql-entailment/spec/ produces no errors, just redirect warnings.
But PR 25 is the last PR that changed spec/index.html
And then checking https://github.com/w3c/sparql-entailment/blob/main/publication-snapshots/FPWD/Overview.html results in some errors but fewer than for the PR.  But the snapshot should have been taken directly from the spec.
Checking https://github.com/w3c/sparql-entailment/blob/main/spec/index.html produces the same errors as the FPWD, as far as I can tell.

So some guidance on what and when to check links would be welcome.

Here are the errors from the FPWD
```

error Lines: 1171, 1213 https://github.com/w3c/sparql-entailment/blob/%7B%7B%20urlEncodedRefName%20%7D%7D/publication-snapshots/FPWD/Overview.html
    Status: 404 Not Found

    The link is broken. Double-check that you have not made any typo, or mistake in copy-pasting. If the link points to a resource that no longer exists, you may want to remove or fix the link. 
error Line: 1482 https://github.com/w3c/sparql-entailment/blob/main/publication-snapshots/FPWD/%7B%7B%20revealButtonHref%20%7D%7D
    Status: 404 Not Found

    The link is broken. Double-check that you have not made any typo, or mistake in copy-pasting. If the link points to a resource that no longer exists, you may want to remove or fix the link. 
info Line: 1478 https://github.co/hiddenchars
    Status: (N/A) Forbidden by robots.txt

    The link was not checked due to robots exclusion rules. Check the link manually. 
```

The weird one is the link into github.co.   What does this come from?  I don't see it in the document source.

And none of the reports include the missing link that caused this issue to be created, even though the link is in the document source and doesn't seem to resolve.

**Comment by pfps** [comment]
In any case PR #28 should fix the broken link.

**Comment by pchampin** [comment]
> In any case PR https://github.com/w3c/sparql-entailment/pull/28 should fix the broken link.

Good. I did fix it manually on the FPWD snapshot just to be on the safe side.

**Comment by pfps** [comment]
This issue appears to be appropriately handled so I'm proposing closing.
