### ISSUE TITLE
SPARQL Entailment Regimes Errata

### ISSUE THREAD

**Issue by afs** [w3c/sparql-entailment#7]
From https://www.w3.org/2013/sparql-errata#sparql11-entailment

- [ ] https://www.w3.org/2013/sparql-errata#errata-entailment-1 - diagram error

**Comment by pfps** [comment]
Is there source for the diagram?

**Comment by afs** [comment]
Unfortunately, no. I asked the original editor and they couldn't find files for the two diagrams.

**Comment by pfps** [comment]
OK.  I did a hack and slash job to move the triple link to more or less the right place.
